version: "3"
services:
  nifi:
    image: apache/nifi
    ports:
      - 8080:8080
      - 10001:10001
    volumes:
      - ./nifi/conf:/opt/nifi/nifi-current/conf

  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./mongo/data:/data/db

